export const LICOLITE_ASPECT_PROTOCOL = "pactium.v0.2.licolite-aspect";
export const LICOLITE_POLICY_EXTENSION = "licolite.policy";
export const LICOLITE_WORKSPACE_EFFECT_EXTENSION = "licolite.workspaceEffect";
export const LICOLITE_SIGNATURE_EXTENSION = "licolite.signature";
export const LICOLITE_CRITICAL_EXTENSIONS = Object.freeze([
  LICOLITE_POLICY_EXTENSION,
  LICOLITE_WORKSPACE_EFFECT_EXTENSION
]);
export const LICOLITE_SUPPORTED_CRITICAL_EXTENSIONS = Object.freeze([
  LICOLITE_POLICY_EXTENSION,
  LICOLITE_WORKSPACE_EFFECT_EXTENSION,
  LICOLITE_SIGNATURE_EXTENSION
]);
