import type { useConsole } from "./useConsole";

type ConsoleContext = ReturnType<typeof useConsole>;

const feedShellKeys = [
  "agentSelectorOptions",
  "busyKey",
  "chooseInfoFeedClarification",
  "contextWindowOptionBarOptions",
  "continueInfoFeedAfterModelSelection",
  "continueInfoFeedAfterRetry",
  "copyInfoFeedSummary",
  "deleteInfoFeedHistoryItem",
  "exportInfoFeedSummary",
  "handleAgentAnswerClick",
  "handleInfoFeedAttachmentFiles",
  "highlightedConfigTarget",
  "infoFeedAgentAnswer",
  "infoFeedAgentSteps",
  "infoFeedAllKeywordItems",
  "infoFeedAttachments",
  "infoFeedClarification",
  "infoFeedContextGateNotice",
  "infoFeedCurrentRun",
  "infoFeedCurrentUserQuestion",
  "infoFeedExpertFeedbackFor",
  "infoFeedExpertFeedbackForRun",
  "infoFeedForm",
  "infoFeedHistory",
  "infoFeedHistoryPanelItems",
  "infoFeedInputPlaceholder",
  "infoFeedKeywordItems",
  "infoFeedKeywordProgressLabel",
  "infoFeedLowRelevanceKeywordItems",
  "infoFeedModelOptions",
  "infoFeedModelSelectionMessage",
  "infoFeedNeedsModelSelection",
  "infoFeedNeedsRetryContinue",
  "infoFeedParentRunForCurrent",
  "infoFeedParentSummaryHtml",
  "infoFeedReadyForSummary",
  "infoFeedRetryMessage",
  "infoFeedRetryStageLabel",
  "infoFeedStreamingSummaryHtml",
  "infoFeedSubmitLabel",
  "infoFeedSummaryIsStreaming",
  "infoFeedSummaryMarkdown",
  "infoFeedSummaryRuntime",
  "infoFeedTurnAttachments",
  "infoFeedTurnQuestion",
  "infoFeedTurnSummaryHtml",
  "infoFeedTurnTitle",
  "infoFeedUserCardTitle",
  "openAgentEvidencePreview",
  "removeInfoFeedAttachment",
  "runInfoFeed",
  "runInfoFeedSummaryAgent",
  "saveSettings",
  "selectedInfoFeedModel",
  "selectInfoFeedHistoryItem",
  "settingsDraft",
  "thinkingModeOptionBarOptions",
] as const satisfies readonly (keyof ConsoleContext)[];

export type FeedShellContext = Pick<ConsoleContext, (typeof feedShellKeys)[number]>;

export function pickFeedShellContext(context: ConsoleContext): FeedShellContext {
  return Object.fromEntries(feedShellKeys.map((key) => [key, context[key]])) as FeedShellContext;
}
