import { formatCompactDate } from "./console-format-utils";
import { useServerConsoleShellContext } from "./serverConsoleShellContext";
import {
  maintenanceAgentRiskLabel,
  maintenanceAgentStatusLabel,
  maintenanceAgentStatusTone,
} from "./console-status-utils";

export function useMaintenanceAgentViewConsole() {
  const {
    agentSelectorOptions,
    approveMaintenanceAgentRun,
    autoApproveRiskOptionBarOptions,
    busyKey,
    canAdminMaintenanceAgent,
    canApproveMaintenanceAgent,
    canRunMaintenanceAgent,
    cancelMaintenanceAgentRun,
    chatMaintenanceAgent,
    currentAgentModelOptionLabel,
    displayedMaintenanceAgentRuns,
    enabledBooleanOptionBarOptions,
    latestMaintenanceAgentRun,
    maintenanceAgentConfig,
    maintenanceAgentMessage,
    maintenanceAgentModelAlias,
    maintenanceAgentResultJson,
    maintenanceAgentRunbook,
    maintenanceAgentRunbookOptionBarOptions,
    maintenanceAgentRunbooks,
    maintenanceAgentSummary,
    nextMaintenanceAgentRunAt,
    pendingMaintenanceApprovalCount,
    plannerModeOptionBarOptions,
    runMaintenanceAgentKnowledgeMaintenance,
    runMaintenanceAgentRunbook,
    saveMaintenanceAgentConfig,
    selectedMaintenanceAgentRun,
  } = useServerConsoleShellContext();

  return {
    agentSelectorOptions,
    approveMaintenanceAgentRun,
    autoApproveRiskOptionBarOptions,
    busyKey,
    canAdminMaintenanceAgent,
    canApproveMaintenanceAgent,
    canRunMaintenanceAgent,
    cancelMaintenanceAgentRun,
    chatMaintenanceAgent,
    currentAgentModelOptionLabel,
    displayedMaintenanceAgentRuns,
    enabledBooleanOptionBarOptions,
    formatCompactDate,
    latestMaintenanceAgentRun,
    maintenanceAgentConfig,
    maintenanceAgentMessage,
    maintenanceAgentModelAlias,
    maintenanceAgentResultJson,
    maintenanceAgentRiskLabel,
    maintenanceAgentRunbook,
    maintenanceAgentRunbookOptionBarOptions,
    maintenanceAgentRunbooks,
    maintenanceAgentStatusLabel,
    maintenanceAgentStatusTone,
    maintenanceAgentSummary,
    nextMaintenanceAgentRunAt,
    pendingMaintenanceApprovalCount,
    plannerModeOptionBarOptions,
    runMaintenanceAgentKnowledgeMaintenance,
    runMaintenanceAgentRunbook,
    saveMaintenanceAgentConfig,
    selectedMaintenanceAgentRun,
  };
}
