import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
// Note: common components are NOT imported here — that would create a circular
// dependency (components → useConsole → components). Each view imports the
// component files it needs directly.
import {
  adminViewTitleMap,
  debugTabs,
  emptyDiscovery,
  emptyExpertVocabulary,
  emptySettings,
  intelligentModuleDefinitions,
  knowledgeTabs,
  migrationStateLabels,
  modelLibraryProviderDefinitions,
  moduleGroupDefinitions,
  moduleNameDescriptions,
  moduleNameLabels,
  viewTitleMap,
} from "./console-defaults";
import {
  CLEAR_LOCAL_STATE_PARAM,
  clearBrowserCacheStorage,
  clearBrowserLocalStateFromUrl as clearBrowserLocalStateFromUrlCore,
  clearIndexedDbDatabases,
  unregisterServiceWorkers,
} from "./console-browser-state-utils";
import {
  confirmConsoleAction,
  copyTextToClipboard,
  createConsoleTargetHighlightController,
  downloadTextFile,
  notifyConsoleAction,
} from "./console-browser-effects";
import {
  isAgentExploreDraftSession,
} from "./console-agent-explore-utils";
import {
  AGENT_SELECTION_REFERENCE_LOG_LIMIT,
  createConsoleAgentSelectionReferenceController,
} from "./console-agent-selection-reference-controller";
import { createConsoleAgentSelectorController } from "./console-agent-selector-controller";
import { createConsoleAuthController } from "./console-auth-controller";
import { createConsoleBusyController } from "./console-busy-controller";
import { createConsoleCodexOAuthController } from "./console-codex-oauth-controller";
import { createConsoleClientController } from "./console-client-controller";
import { createConsoleAgentExploreLayoutController } from "./console-agent-explore-layout-controller";
import { createConsoleAgentExploreOutputController } from "./console-agent-explore-output-controller";
import { createConsoleAgentExploreSessionController } from "./console-agent-explore-session-controller";
import { createConsoleAgentExploreStateController } from "./console-agent-explore-state-controller";
import { createConsoleContextCompilerController } from "./console-context-compiler-controller";
import { createConsoleDiscoveryController } from "./console-discovery-controller";
import { createConsoleExpertRulesController } from "./console-expert-rules-controller";
import { createConsoleFeatureAccessController } from "./console-feature-access-controller";
import { createConsoleKnowledgeSourceController } from "./console-knowledge-source-controller";
import { createConsolePathPickerActionController } from "./console-path-picker-action-controller";
import { createConsolePathPickerController } from "./console-path-picker-controller";
import { createConsoleRuntimeMountController } from "./console-runtime-mount-controller";
import { createConsoleDashboardAlertController } from "./console-dashboard-alert-controller";
import { createConsoleInfoFeedController } from "./console-info-feed-controller";
import { createConsoleKnowledgeEvidenceController } from "./console-knowledge-evidence-controller";
import { createConsoleKnowledgeIngestController } from "./console-knowledge-ingest-controller";
import { createConsoleJobController } from "./console-job-controller";
import { createConsoleKnowledgeLogController } from "./console-knowledge-log-controller";
import { createConsoleKnowledgeMaintenanceController } from "./console-knowledge-maintenance-controller";
import { createConsoleKnowledgeRecallController } from "./console-knowledge-recall-controller";
import {
  createConsoleKnowledgeSearchPanelStateController,
  createConsoleKnowledgeSearchStateController,
} from "./console-knowledge-search-state-controller";
import { createConsoleKnowledgeReviewController } from "./console-knowledge-review-controller";
import { createConsoleMaintenanceAgentController } from "./console-maintenance-agent-controller";
import { createConsoleMcpAuthorizationController } from "./console-mcp-authorization-controller";
import { createConsoleModelLibraryController } from "./console-model-library-controller";
import { createConsoleNavigationController } from "./console-navigation-controller";
import { createConsoleOptionBarController } from "./console-option-bar-controller";
import { createConsoleOpsMonitorController } from "./console-ops-monitor-controller";
import { createConsoleRuleAuthoringController } from "./console-rule-authoring-controller";
import { createConsoleRefreshStateController } from "./console-refresh-state-controller";
import { createConsoleRuntimeLifecycleController } from "./console-runtime-lifecycle-controller";
import { createConsoleServerEventController } from "./console-server-event-controller";
import { createConsoleSettingsBridgeController } from "./console-settings-bridge-controller";
import { createConsoleSettingsDraftController } from "./console-settings-draft-controller";
import { createConsoleSettingsPersistenceController } from "./console-settings-persistence-controller";
import { createConsoleStateEventReducerController } from "./console-state-event-reducer-controller";
import { createConsoleSystemLogRowController } from "./console-system-log-row-controller";
import { createConsoleToolManagementController } from "./console-tool-management-controller";
import { createConsoleWordCloudController } from "./console-word-cloud-controller";

export const consoleKnowledgeGovernanceContract = Object.freeze({
  knowledgeBase: "knowledgeBase",
  runtimeMountActions: ["saveRuntimeMounts", "reloadRuntimeMounts", "enableMountModule", "disableMountModule"],
  uploadFlow: "async function uploadFilesToKnowledge() -> createKnowledgeUploadSession(filesToUpload -> jobs-client.createJob({",
});

import {
  asRecord,
  modelAgentUid,
  modelEntryParameters,
  modelEntryStringField,
  moduleAgentProfileJson,
  normalizeAgentModuleAccess,
  normalizeAgentPermissionGroupDraft,
  normalizeAgentPermissionGroupsDraft,
  normalizeAgentModelEntry,
  normalizeModelLibraryEntries,
  normalizeModuleAgentProfile,
  normalizeModuleAgentProfilesForDraft,
  redactAgentModelEntryForExport,
  redactedProviderSettingsForAgentExport,
} from "./console-model-utils";
import type {
  AgentSettings,
  AgentModelConfig,
  AgentModuleAccess,
  KnowledgeSource,
  ModelProbeResponse,
  ServerConsoleState,
  UnifiedRegistrationRecord,
} from "../lib/types";
import type {
  DrawerTab, AppView, AdminView, DebugTab, RuleAuthoringMode,
  KnowledgeTab, KnowledgeManagementPanel, OptionBarValue, OptionBarOption,
  KnowledgeLogRow, AgentExploreSession,
  HistorySessionPanelItem, ModelEntryBinding, AgentConfigurationAlert,
  DashboardAlert, PathPickerMode,
  RefreshStateOptions, CloudProvider,
} from "../types/app";
export type {
  DrawerTab, AppView, AdminView, DebugTab, RuleAuthoringMode,
  KnowledgeTab, KnowledgeManagementPanel, OptionBarValue, OptionBarOption,
  KnowledgeLogRow, AgentExploreSession, KnowledgeRecallDebugRun,
  HistorySessionPanelItem, ModelEntryBinding, AgentConfigurationAlert,
  DashboardAlert, WorkQueueRow, InfoFeedStageStatus, InfoFeedAttachment,
  InfoFeedClarificationOption, InfoFeedExpertFeedbackAnchor, InfoFeedClarification,
  InfoFeedExpertFeedback, InfoFeedTurnSnapshot, InfoFeedRetryStage,
  InfoFeedRetryState, InfoFeedRunState, PathPickerMode, PathPickerState,
  WordCloudCorpusAuditAction, RefreshStateOptions, CloudProvider,
} from "../types/app";

// ─────────────────────────────────────────────────────────────────────────────
// Module-level singleton state and logic.
// All refs, computeds, functions, and watches here are shared across every
// component that calls useConsole().  Only onMounted / onUnmounted stay inside
// the exported function so Vue can bind them to the component lifecycle.
// ─────────────────────────────────────────────────────────────────────────────

const consoleState = ref<ServerConsoleState | null>(null);
const serverAvailable = ref(false);
const {
  activeConsoleFeatureIds,
  hasAnyFeature,
  hasFeature,
  isAdminViewEnabled,
  visibleDebugTabs,
  visibleKnowledgeTabs,
} = createConsoleFeatureAccessController({
  consoleState,
  debugTabs,
  isAuthenticated: () => isAuthenticated.value,
  knowledgeTabs,
});
const settingsDraft = ref<AgentSettings>({ ...emptySettings });
const {
  agentExploreActiveTabId,
  agentExploreClosedTabIds,
  agentExploreConfiguredLimit,
  agentExploreConfiguredMaxIterations,
  agentExploreConfiguredMaxTokens,
  agentExploreConfiguredTemperature,
  agentExploreConfiguredToolChoice,
  agentExploreContextWindowOptions,
  agentExploreDefaults,
  agentExploreDraftTabs,
  agentExploreForm,
  agentExploreHiddenRunIds,
  agentExploreHistory,
  agentExploreHydrated,
  agentExploreResult,
  agentExploreThinkingModeOptions,
  agentExploreThinkingParameters,
  applyAgentExploreDefaultsFromSettings,
  boundedAgentExploreNumber,
  normalizeAgentExploreThinkingMode: normalizedAgentExploreThinkingMode,
  selectedAgentExploreContextProfile,
  selectedAgentExploreThinkingMode,
} = createConsoleAgentExploreStateController({
  settingsDraft,
});
const error = ref("");
const {
  busyKey,
  clearAllBusy,
  clearBusy,
  isBusy,
  isBusyPrefix,
  setBusy,
} = createConsoleBusyController();
const {
  beginCodexOAuthLogin,
  codexOAuthLogin,
  codexOAuthPollTimer,
  codexOAuthStatus,
  ensureCodexOAuthReady,
  refreshCodexOAuthStatus,
  startCodexOAuthPolling,
  stopCodexOAuthPolling,
} = createConsoleCodexOAuthController({
  clearBusy,
  error,
  setBusy,
});
const selectedModelProvider = ref<CloudProvider>("deepseek");
const modelProbeResults = ref<Record<string, ModelProbeResponse>>({});
const modelLibraryExpandedCards = ref<Record<string, boolean>>({});
const moduleAgentCandidateDrafts = ref<Record<string, string>>({});
const agentModelOptionLabelCache = ref<Record<string, string>>({});
const settingsDraftDirty = ref(false);
const settingsBridgeController = createConsoleSettingsBridgeController();
const {
  applyRemoteConsoleDraftUpdate,
  bindSettingsDraftActions,
  bindSettingsPersistenceActions,
  disableMountModule,
  enableMountModule,
  isApplyingRemoteConsoleDrafts,
  moduleAgentProfilesPayload,
  normalizeHttpAdapterSettings,
  normalizeModelLibraryAgents,
  normalizedSettingsFromServer,
  reloadModules,
  remoteDraftEquals,
  replaceSettingsDraftFromServer,
  saveAgentPermissionSettings,
  saveModelLibrarySettings,
  saveModuleSettings,
  saveMountModules,
  saveSettings,
  settingsDraftEquals,
  settingsPayloadForSave,
} = settingsBridgeController;
const applyingRemoteConsoleDrafts = settingsBridgeController.applyingRemoteConsoleDrafts;
const filter = ref("");
const highlightedConfigTarget = ref("");
const configTargetHighlightController = createConsoleTargetHighlightController({
  highlightedTarget: highlightedConfigTarget,
});
const editingMountPaths = ref<Record<string, boolean>>({});
const {
  adminView,
  bindNavigationRouter,
  closeDrawer,
  closeSideNavOverlay,
  currentView,
  debugTab,
  drawerOpen,
  drawerTab,
  ensureKnowledgeTabState,
  externalServiceTab,
  isKnownDebugRouteTab,
  jumpToKnowledgeFileImport,
  knowledgeManagementPanel,
  knowledgeTab,
  openAdmin,
  openAgentConfigurationAlert,
  openDebugTab,
  openDrawer,
  openExternalServiceTab,
  openKnowledgeManagementPanel,
  openKnowledgeTab,
  refreshSystemStatusLogs,
  sideNavOpen,
  syncNavigationStateFromRoute,
  switchView,
  viewTitle,
} = createConsoleNavigationController({
  error,
  ensureAgentPermissionGroupsDraft: () => ensureAgentPermissionGroupsDraft(),
  hasFeature,
  isAdminViewEnabled,
  refreshAuthAdmin: () => refreshAuthAdmin(),
  refreshBackgroundProcesses: (options) => refreshBackgroundProcesses(options),
  refreshClientRuntimeStatus: (options) => refreshClientRuntimeStatus(options),
  refreshContextCompiler: (options) => refreshContextCompiler(options),
  refreshDashboardAlertsSnapshot: (options) => refreshDashboardAlertsSnapshot(options),
  refreshExpertRules: (options) => refreshExpertRules(options),
  refreshKnowledgeConsole: () => refreshKnowledgeConsole(),
  refreshKnowledgeRecallBackendSpaces: () => refreshKnowledgeRecallBackendSpaces(),
  refreshMaintenanceAgent: (options) => refreshMaintenanceAgent(options),
  refreshMonitorAlerts: (options) => refreshMonitorAlerts(options),
  refreshState: (options) => refreshState(options),
  refreshToolManagement: (options) => refreshToolManagement(options),
  refreshWordCloud: (options) => refreshWordCloud(options),
  scrollToConfigTarget: (targetId) => scrollToConfigTarget(targetId),
  visibleDebugTabs,
  visibleKnowledgeTabs,
});
const {
  knowledgeConfigGroupDescription,
  knowledgeConsole,
  knowledgeMaintenanceDraft,
  knowledgeManagementPanelOptionBarOptions,
  knowledgeModules,
  knowledgeRecentJobs,
  knowledgeSchema,
  knowledgeSourceState,
  knowledgeStatus,
  knowledgeTabDisplayLabel,
  maintenanceFieldValue,
  maintenanceJson,
  readNestedValue,
  refreshKnowledgeConsole,
  saveKnowledgeMaintenance,
  setMaintenanceFieldFromEvent,
  setMaintenanceFieldValue,
  writeNestedValue,
} = createConsoleKnowledgeMaintenanceController({
  clearAllBusy,
  consoleState,
  debugTab,
  error,
  hasScope: (scope: string) => hasScope(scope),
  knowledgeManagementPanel,
  refreshKnowledgeConflicts: (options) => refreshKnowledgeConflicts(options),
  refreshKnowledgeRecallBackendSpaces: () => refreshKnowledgeRecallBackendSpaces(),
  setBusy,
});
const {
  knowledgeSearchForm,
  knowledgeSearchResponse,
  knowledgeSearchResults,
  lastKnowledgeSearchQuery,
} = createConsoleKnowledgeSearchStateController();
const {
  contextBuildRecordRows,
  contextBuildRecordsResponse,
  contextEvaluationResult,
  contextPreviewPayload,
  contextPreviewRequiredEvidence,
  contextPreviewResult,
  contextPreviewTask,
  contextProfileRows,
  contextProfilesResponse,
  exportContextBuildRecords,
  previewContextCompiler,
  refreshContextCompiler,
  runContextReplayEvaluation,
} = createConsoleContextCompilerController({
  clearAllBusy,
  error,
  recentTurns: () => infoFeedCurrentRun.value?.turns || [],
  selectedContextProfileId: () => selectedAgentExploreContextProfile.value.value,
  setBusy,
});
const {
  agentSelectionReferenceLogs,
  agentSelectionReferenceStates,
  emitAgentSelectionReferenceLog,
  normalizeAgentSelectionAlias,
  trackAgentSelectionReference,
  watchAgentSelectionReference,
} = createConsoleAgentSelectionReferenceController();
const {
  agentExploreActiveIteration,
  agentExploreAnswerHtml,
  agentExploreContextBuildRecordId,
  agentExploreEventTime,
  agentExploreEvidenceRefs,
  agentExploreLinkedEvidenceRefs,
  agentExploreMaxIterations,
  agentExploreProgress,
  agentExploreProgressVisible,
  agentExploreRunCoverage,
  agentExploreRunInput,
  agentExploreStepOpen,
  agentExploreSteps,
  agentExploreWorkspaceId,
  currentAgentExploreQuery,
  recordConsoleKnowledgeFeedback,
  agentExploreDocumentMarkdown,
  copyAgentExploreDocument,
  exportAgentExploreDocument,
} = createConsoleAgentExploreOutputController({
  agentExploreForm,
  agentExploreResult,
  busyKey,
  error,
  infoFeedQuery: () => infoFeedCurrentRun.value?.query || "",
  infoFeedRunId: () => infoFeedCurrentRun.value?.runId || "",
  knowledgeSearchQuery: () => knowledgeSearchForm.value.query || "",
});
const {
  agentEvidencePreviewOpen,
  assetUrlForReference,
  closeAgentEvidencePreview,
  emailToSafeHtml,
  embedEvidenceAssets,
  evidenceAssets,
  evidenceLoadError,
  evidenceLoadSequence,
  evidenceMainText,
  evidencePrimaryText,
  evidenceReadableHtml,
  evidenceReadableKind,
  evidenceReadableKindLabel,
  evidenceReasonText,
  evidenceSourceDetails,
  evidenceSourceHint,
  handleAgentAnswerClick,
  hydrateSearchResultPreview,
  imageEvidenceAssets,
  loadEvidence,
  openAgentEvidencePreview,
  openKnowledgeSearchResult,
  renderEmailFrame,
  renderEmailImage,
  renderEmailNode,
  renderEvidenceImageGallery,
  renderEvidenceReadableHtml,
  renderReadableHtmlDocument,
  rewriteInlineAssetRefs,
  safeEmailImageSrc,
  sanitizeEmailCssUrls,
  sanitizeEmailFrameDocument,
  selectedEvidence,
  selectedEvidenceBlocks,
  selectedEvidenceDisplayTitle,
  selectedEvidenceDocument,
  selectedEvidenceId,
  selectedEvidencePayload,
  selectedEvidenceSection,
} = createConsoleKnowledgeEvidenceController({
  busyKey,
  clearAllBusy,
  currentAgentExploreQuery,
  error,
  infoFeedQuery: () => infoFeedCurrentRun.value?.query || "",
  knowledgeSearchResults,
  agentExploreContextBuildRecordId,
  openDebugTab,
  recordFeedback: recordConsoleKnowledgeFeedback,
  setBusy,
});
const {
  applyIngestJobFromEvent,
  canSubmitKnowledgeIngest,
  ingestFiles,
  ingestJob,
  ingestProgress,
  knowledgeIngestExternalProvider,
  knowledgeIngestExternalRefs,
  knowledgeIngestExternalTargetLabels,
  knowledgeIngestTargets,
  knowledgeIngestTargetSummary,
  knowledgeIngestTargetValidationMessage,
  knowledgeIngestTeamRefs,
  knowledgeIngestUserRefs,
  normalizedManifest,
  onIngestFilesSelected,
  refreshIngestJob,
  uploadFilesToKnowledge,
} = createConsoleKnowledgeIngestController({
  clearAllBusy,
  error,
  refreshKnowledgeConsole,
  refreshState,
  setBusy,
  settingsDraft,
});
const {
  activeKnowledgeSources,
  addKnowledgeSource,
  applyJobToKnowledgeSources,
  applyKnowledgeSourceState,
  applyLocalSourceDirectoryPath,
  deleteKnowledgeSource,
  directoryNameFromPath,
  localSourceForm,
  refreshKnowledgeSource,
  refreshKnowledgeSources,
  syncLocalSourceLabelFromPath,
  updateKnowledgeSource,
} = createConsoleKnowledgeSourceController({
  clearAllBusy,
  error,
  ingestJob,
  knowledgeConsole,
  knowledgeSourceState,
  setBusy,
});
const {
  closeServerPathPicker,
  confirmServerPathPicker,
  openPathEntry,
  openServerPathPicker,
  pathEntryMeta,
  pathPicker,
  pathPickerModeLabel,
  refreshServerPathBrowser,
  selectServerPath,
} = createConsolePathPickerController();
const {
  analysisModuleDescription,
  currentAnalysisModule,
  enabledMountCount,
  isMountPathEditing,
  moduleGroups,
  moduleRows,
  mountDraft,
  mountDraftDirty,
  openMountPathPicker,
  replaceMountDraftFromServer,
  toggleMountPathEdit,
  totalMountCount,
} = createConsoleRuntimeMountController({
  applyRemoteConsoleDraftUpdate,
  consoleState,
  editingMountPaths,
  isApplyingRemoteConsoleDrafts,
  openServerPathPicker,
  remoteDraftEquals,
  saveMountModules,
  settingsDraft,
});

const normalizeModelEntry = (
  entry: Partial<AgentModelConfig>,
  index = 0,
  sourceSettings: AgentSettings = settingsDraft.value,
) => normalizeAgentModelEntry(entry, index, sourceSettings);

const {
  agentExploreSplitDragging,
  agentExploreSplitLeftPercent,
  agentExploreSplitRef,
  agentExploreSplitStyle,
  agentExploreTraceOpen,
  clampAgentExploreSplitPercent,
  handleAgentExploreSplitKeydown,
  handleAgentExploreSplitPointerMove,
  handleAgentExploreTraceToggle,
  startAgentExploreSplitResize,
  stopAgentExploreSplitResize,
  updateAgentExploreSplitFromClientX,
} = createConsoleAgentExploreLayoutController();

async function clearBrowserLocalStateFromUrl() {
  return clearBrowserLocalStateFromUrlCore({
    clearMemoryCaches: clearInfoFeedKeywordCache,
  });
}

watch(
  agentExploreForm,
  () => {
    persistAgentExploreState();
  },
  { deep: true },
);

watch(
  agentExploreResult,
  () => {
    persistAgentExploreState();
  },
  { deep: true },
);

watch(knowledgeManagementPanel, (panel) => {
  if (currentView.value !== "knowledge" || knowledgeTab.value !== "management") {
    return;
  }
  if (panel === "rules") {
    void refreshExpertRules();
  } else {
    void refreshKnowledgeConsole();
  }
});

const {
  discoveryDraft,
  discoveryDraftDirty,
  replaceDiscoveryDraftFromServer,
  saveDiscovery,
} = createConsoleDiscoveryController({
  applyRemoteConsoleDraftUpdate,
  clearAllBusy,
  error,
  isApplyingRemoteConsoleDrafts,
  refreshState,
  remoteDraftEquals,
  setBusy,
});

const {
  addVocabularyEntry,
  cloneExpertVocabulary,
  deleteVocabularyEntry,
  displayedVocabularyEntries,
  emailDepartmentRules,
  emailReportSeriesRules,
  emailRulesDraft,
  emailSynonymRules,
  expertRuleEnabled,
  expertVocabularyDraft,
  expertVocabularyDraftDirty,
  goldenRuleItems,
  goldenRulePackageTitle,
  goldenRulePackages,
  goldenRulesState,
  hiddenVocabularyEntryCount,
  parseEmailRulesDraft,
  refreshExpertRules,
  replaceExpertVocabularyDraftFromServer,
  replaceRulesDraftFromServer,
  rulesDraftDirty,
  rulesText,
  saveExpertVocabulary,
  saveRules,
  setEmailRuleEntryEnabled,
  setVocabularyEntryEnabled,
  showAllVocabularyEntries,
  splitVocabularyList,
  toggleGoldenRuleEnabled,
  updateVocabularyDomains,
  updateVocabularyEntry,
  updateVocabularyKeywords,
  updateVocabularyPath,
  vocabularyEntryPath,
  vocabularySearch,
} = createConsoleExpertRulesController({
  applyRemoteConsoleDraftUpdate,
  clearAllBusy,
  error,
  isApplyingRemoteConsoleDrafts,
  refreshState,
  setBusy,
});

const {
  applyConsoleState,
  applyServerEvent,
  baseServerEventTopics,
  currentServerEventTopics,
  uploadTraceEvents,
} = createConsoleStateEventReducerController({
  applyAgentExploreDefaultsFromSettings,
  applyMaintenanceAgentConfigFromEvent: (config) => applyMaintenanceAgentConfigFromEvent(config),
  applyMaintenanceAgentStateFromConsoleState: (state) => applyMaintenanceAgentStateFromConsoleState(state),
  applyWordCloudEvent: (wordBagSet) => applyWordCloudEvent(wordBagSet),
  consoleState,
  discoveryDraftDirty,
  expertVocabularyDraftDirty,
  hasFeature,
  knowledgeConsole,
  knowledgeSourceState,
  mountDraftDirty,
  normalizedSettingsFromServer,
  refreshExpertRules,
  refreshKnowledgeConflicts: (options) => refreshKnowledgeConflicts(options),
  refreshMaintenanceAgent: (options) => refreshMaintenanceAgent(options),
  removeJobFromEvent: (jobId) => removeJobFromEvent(jobId),
  replaceDiscoveryDraftFromServer,
  replaceExpertVocabularyDraftFromServer,
  replaceMountDraftFromServer,
  replaceRulesDraftFromServer,
  replaceSettingsDraftFromServer,
  rulesDraftDirty,
  settingsDraftDirty,
  upsertJobFromEvent: (job) => upsertJobFromEvent(job),
});

const {
  clearServerEventTimer,
  isAbortError,
  nextCursorFromProtocolEvents,
  resetServerEventCursor,
  runServerEventSubscription,
  serverEventAbortController,
  serverEventCursor,
  serverEventSubscriptionGeneration,
  serverEventSubscriptionStopped,
  serverEventTimer,
  serverEventTimerResolve,
  startServerEventSubscription,
  stopServerEventSubscription,
  waitForServerEventRetry,
} = createConsoleServerEventController({
  applyServerEvent,
  currentTopics: currentServerEventTopics,
  refreshState,
});

const {
  agentExploreAgentOptions,
  agentModelOptionValueSet,
  agentOptionsForModule,
  agentSelectorOptions,
  cacheAgentModelOptionLabels,
  currentAgentModelOptionLabel,
  hasAgentModelOption,
  inactiveAgentModelOption,
  normalizeAgentSelectorOption,
  selectedAgentExploreModel,
  selectedAgentFromOptions,
  validAgentModelAlias,
} = createConsoleAgentSelectorController({
  agentExploreForm,
  agentModelOptionLabelCache,
  consoleState,
});

const {
  addModelEntryBinding,
  addModelProvider,
  addModuleAgentProfileFromDraft,
  addableModelProviders,
  agentExploreModelOptionLabel,
  agentModelAssignmentOptions,
  collectModelEntryBindings,
  customHttpAdapterAlias,
  customHttpAdapterLabel,
  duplicateModelEntry,
  ensureModuleAgentGroup,
  ensureModuleAgentProfile,
  exportAgentModelEntryConfig,
  hasOpenAiModelUsage,
  isModelLibraryCardExpanded,
  modelEntryBindingSummary,
  modelEntryBindings,
  modelEntryBindingsByKey,
  modelEntryAllowsModule,
  modelEntryConfigured,
  modelEntryIsBound,
  modelEntryMatchesAssignment,
  modelEntryMatchesUid,
  modelEntryModuleAccess,
  modelEntryProbeResult,
  modelEntryProbeStatusLabel,
  modelEntryProbeStatusTone,
  modelEntryStatusKey,
  modelEntryStatusLabel,
  modelEntryStatusTone,
  modelEntryUidSet,
  modelProbeFailureResult,
  modelProbeSettingsForEntry,
  modelProviderDefinition,
  modelProviderFromRef,
  modelRef,
  moduleAgentProfileRows,
  moduleModelAssignmentOptions,
  moduleModelAssignmentStats,
  moduleModelRef,
  moduleNeedsIntelligence,
  parseModelRef,
  probeModel,
  probeModelEntry,
  probeModelLibraryBeforeSave,
  providerConfigured,
  providerLabel,
  providerStatusLabel,
  providerStatusTone,
  removeModelProvider,
  removeModuleAgentProfile,
  runModelEntryProbe,
  setModelEntryModuleAccessMode,
  setModuleAgentProfileEnabled,
  setModuleModelRef,
  setModuleNeedsIntelligence,
  toggleModelEntryModuleAccess,
  toggleModelLibraryCard,
  visibleModelEntries,
  visibleModelProviders,
} = createConsoleModelLibraryController({
  agentExploreModelAlias: () => agentExploreForm.value.modelAlias,
  codexOAuthStatus,
  clearAllBusy,
  currentAgentModelOptionLabel,
  ensureCodexOAuthReady,
  error,
  infoFeedModelAlias: () => infoFeedForm.value.modelAlias,
  infoFeedRunningSummary: () => ({
    modelAlias: infoFeedCurrentRun.value?.summary.modelAlias,
    runId: infoFeedCurrentRun.value?.runId,
    status: infoFeedCurrentRun.value?.summary.status,
  }),
  modelLibraryExpandedCards,
  modelProbeResults,
  moduleAgentCandidateDrafts,
  normalizeModelEntry,
  replaceSettingsDraftFromServer,
  ruleAuthoringModelAlias: () => ruleAuthoringForm.value.modelAlias,
  selectedModelProvider,
  setBusy,
  settingsDraft,
  settingsPayloadForSave,
});

bindSettingsDraftActions(createConsoleSettingsDraftController({
  modelEntryParameters,
  modelRef,
  moduleModelAssignmentOptions,
  moduleNeedsIntelligence,
  normalizeModelEntry,
  settingsDraft,
  settingsDraftDirty,
  visibleModelEntries: () => visibleModelEntries.value,
}));

const {
  activeToolManagementToolCount,
  addAgentPermissionGroup,
  agentPermissionGroupOptionBarOptions,
  agentPermissionGroups,
  copyIssuedToolToken,
  createGrant,
  defaultAgentPermissionGroups,
  deleteGrant,
  enabledToolGrantCount,
  ensureAgentPermissionGroupsDraft,
  grantHasScope,
  grantHasToolset,
  grantToolRuleState,
  internalToolManagementToolCount,
  issuedToolToken,
  newGrantLabel,
  newGrantScopes,
  newGrantToolsets,
  permissionGroupHasScope,
  permissionGroupHasToolset,
  permissionGroupLabel,
  policyPreviewGrant,
  policyPreviewGrantId,
  policyPreviewProfileId,
  policyPreviewProfileOptionBarOptions,
  policyPreviewResult,
  policyPreviewToolId,
  policyPreviewToolOptionBarOptions,
  previewToolDefinition,
  previewToolPolicy,
  refreshToolManagement,
  removeAgentPermissionGroup,
  rotateGrant,
  selectToolForManagement,
  selectedToolManagementTool,
  selectedToolManagementToolId,
  setGrantToolRule,
  setModelEntryPermissionGroup,
  toggleGrantScope,
  toggleGrantToolset,
  toggleNewGrantScope,
  toggleNewGrantToolset,
  togglePermissionGroupScope,
  togglePermissionGroupToolset,
  toolCatalog,
  toolGrants,
  toolManagementAuditItems,
  toolManagementCatalogState,
  toolManagementGrantsState,
  toolManagementMetricsState,
  toolManagementProfiles,
  toolManagementRiskRows,
  toolManagementStatusRows,
  toolManagementTools,
  toolManagementToolsets,
  toolScopes,
  updateGrant,
} = createConsoleToolManagementController({
  clearAllBusy,
  error,
  setBusy,
  settingsDraft,
  visibleModelEntries,
});
const {
  mcpAuthorizationRequests,
  mcpAuthorizationStatus,
  mcpAuthorizationStatusOptionBarOptions,
  refreshMcpAuthorizationRequests,
  resolveMcpAuthorizationRequest,
} = createConsoleMcpAuthorizationController({
  clearBusy,
  error,
  setBusy,
});

const {
  authAudit,
  authBootstrapping,
  authSessions,
  authState,
  authUsers,
  canAdminAuth,
  canAdminKnowledge,
  canAdminMaintenanceAgent,
  canAdminRuntime,
  canApproveMaintenanceAgent,
  canBrowseServerPaths,
  canMaintainKnowledge,
  canReadKnowledge,
  canReadMaintenanceAgent,
  canRunMaintenanceAgent,
  canWriteJobs,
  canWriteKnowledge,
  currentUser,
  currentUserScopes,
  hasScope,
  isAuthenticated,
  loginForm,
  logoutConsole,
  oidcAllowedDomainsText,
  oidcDraft,
  oidcRoleMappingText,
  refreshAuthAdmin,
  refreshAuthState,
  revokeConsoleSession,
  saveOidcConfig,
  submitLoginAuth,
  updateConsoleUser,
  updateConsoleUserRole,
  updateConsoleUserRoleFromEvent,
} = createConsoleAuthController({
  clearAllBusy,
  consoleState,
  error,
  refreshState,
  resetServerEventCursor,
  setBusy,
  startServerEventSubscription,
  stopServerEventSubscription,
});
const {
  allMaintenanceAgentRuns,
  applyMaintenanceAgentConfigFromEvent,
  applyMaintenanceAgentStateFromConsoleState,
  approveMaintenanceAgentRun,
  cancelMaintenanceAgentRun,
  chatMaintenanceAgent,
  displayedMaintenanceAgentRuns,
  latestMaintenanceAgentRun,
  maintenanceAgentConfig,
  maintenanceAgentMessage,
  maintenanceAgentModelAlias,
  maintenanceAgentResultJson,
  maintenanceAgentRunbook,
  maintenanceAgentRunbookOptionBarOptions,
  maintenanceAgentRunbooks,
  maintenanceAgentRuns,
  maintenanceAgentSchedules,
  maintenanceAgentSummary,
  nextMaintenanceAgentRunAt,
  patchMaintenanceAgentState,
  pendingMaintenanceApprovalCount,
  refreshMaintenanceAgent,
  runMaintenanceAgentKnowledgeMaintenance,
  runMaintenanceAgentRunbook,
  saveMaintenanceAgentConfig,
  selectedMaintenanceAgentRun,
} = createConsoleMaintenanceAgentController({
  canReadMaintenanceAgent,
  clearAllBusy,
  consoleState,
  error,
  modelEntryStatusKey,
  setBusy,
  visibleModelEntries,
});
const {
  acknowledgeMonitorAlert,
  activeMonitorAlerts,
  backgroundProcesses,
  backgroundProcessStatus,
  backgroundRunningCount,
  backgroundSupervisorLabel,
  clientRuntimeHeatRows,
  clientRuntimeStatus,
  clientRuntimeSummary,
  monitorAlertConfigText,
  monitorAlertState,
  monitorAlertSummary,
  queueMonitorItems,
  queueMonitorState,
  recentMonitorAlertHistory,
  refreshBackgroundProcesses,
  refreshClientRuntimeStatus,
  refreshMonitorAlerts,
  recoverBackgroundSupervisor,
  saveMonitorAlertConfig,
  workQueueRows,
  workQueueSummary,
} = createConsoleOpsMonitorController({
  allMaintenanceAgentRuns,
  canAdminMaintenanceAgent,
  canReadMaintenanceAgent,
  clearAllBusy,
  consoleState,
  error,
  setBusy,
});
const {
  buildKnowledgeRecallSearchPayload,
  currentKnowledgeLearningEnabled,
  currentKnowledgeRetrievalSettings,
  currentKnowledgeSearchLimit,
  knowledgeRecallDebugForm,
  knowledgeRecallDebugGridStyle,
  knowledgeRecallDebugModeOptionBarOptions,
  knowledgeRecallDebugRuns,
  knowledgeRecallDebugTargetOptions,
  refreshKnowledgeRecallBackendSpaces,
  runKnowledgeRecallDebugBatch,
  searchKnowledge,
} = createConsoleKnowledgeRecallController({
  activeKnowledgeSources,
  canReadKnowledge,
  clearAllBusy,
  clearSelectedEvidence: () => {
    selectedEvidence.value = null;
    selectedEvidenceId.value = "";
  },
  error,
  knowledgeConsole,
  knowledgeMaintenanceDraft,
  knowledgeSearchForm,
  knowledgeSearchResponse,
  knowledgeSearchResults,
  lastKnowledgeSearchQuery,
  loadEvidence,
  openDebugTab,
  setBusy,
});
const errorNeedsKnowledgeImportAction = computed(() =>
  /语料词频表为空|完成文档入库|重建语料词频/.test(error.value),
);

const {
  publishRuleAuthoringPackage,
  ruleActionOptionBarOptions,
  ruleActionOptions,
  ruleAuthoringCanSubmit,
  ruleAuthoringEffectiveMessage,
  ruleAuthoringForm,
  ruleAuthoringHistory,
  ruleAuthoringManualSummary,
  ruleAuthoringModelOptions,
  ruleAuthoringResult,
  ruleCreationMode,
  ruleMatchStrategyOptionBarOptions,
  ruleMatchStrategyOptions,
  ruleScopeOptionBarOptions,
  ruleScopeOptions,
  runRuleAuthoringChat,
  selectedRuleAuthoringModel,
} = createConsoleRuleAuthoringController({
  agentSelectorOptions,
  canMaintainKnowledge,
  clearAllBusy,
  error,
  setBusy,
  settingsDraft,
});
const {
  addChildWordCloud,
  addManualWordCloud,
  addTermActionToCloud,
  addTermInputToCloud,
  addTermToCloud,
  addWordCloudCorpusPaths,
  applySavedWordCloudSet,
  applyWordCloudEvent,
  autoFillCloudWithAgent,
  clearRemovedTermsFromCloud,
  clearWordCloudCorpusPaths,
  cloneWordCloudSet,
  collapsedWordBagIds,
  createDefaultWordCloudSet,
  fillingWordBagIds,
  findWordCloudInTree,
  flattenWordCloudCards,
  mutateWordCloudDraft,
  normalizeWordCloudCloudForUi,
  normalizeWordCloudCorpusPathForUi,
  normalizeWordCloudCorpusPathsForUi,
  normalizeWordCloudSetForUi,
  normalizeWordCloudTermForUi,
  persistWordCloudCorpusPaths,
  pinWordCloud,
  pinnedWordBagIds,
  preferredWordCloudCorpusPaths,
  proposeWordCloud,
  refreshWordCloud,
  refreshWordCloudCorpusTerms,
  removeSelectedWordCloud,
  removeTermFromCloud,
  removeWordCloudCorpusPath,
  resolveWordCloudCorpusPathsForQuery,
  saveWordCloud,
  selectWordCloud,
  selectedWordBagId,
  selectedWordCloud,
  selectedWordCloudModel,
  setWordCloudDraftCorpusPaths,
  setWordCloudDraftFromState,
  setWordCloudTermInput,
  toggleWordCloudActionMenu,
  toggleWordCloudCollapsed,
  updateSelectedWordCloudField,
  updateWordCloudField,
  wordBagActionMenuId,
  wordCloudCanvasClouds,
  wordCloudCardRows,
  wordCloudCardStyle,
  wordCloudCorpusPathLabel,
  wordCloudCorpusPathSummary,
  wordCloudCorpusPaths,
  wordCloudDraft,
  wordCloudMessages,
  wordCloudModelAlias,
  wordCloudModelOptions,
  wordCloudPalette,
  wordCloudPrompt,
  wordCloudState,
  wordCloudTermFrequencyMap,
  wordCloudTermIdentity,
  wordCloudTermInputs,
  wordCloudTermWithFrequency,
  wordCloudTerms,
  wordCloudVisibleTerms,
} = createConsoleWordCloudController({
  agentSelectorOptions,
  busyKey,
  canReadKnowledge,
  canWriteKnowledge,
  clearAllBusy,
  error,
  setBusy,
});

const {
  INFO_FEED_CONTEXT_CHARS_PER_TOKEN,
  INFO_FEED_FETCH_RETRY_LIMIT,
  INFO_FEED_STORAGE_KEY,
  appendInfoFeedTurnSnapshot,
  applyInfoFeedSummaryAnswer,
  archiveInfoFeedExpertFeedback,
  buildFallbackInfoFeedClarification,
  buildInfoFeedAgentQuery,
  buildInfoFeedSourceContext,
  buildInfoFeedSourceSearchQuery,
  buildInfoFeedSummaryQuestion,
  chooseInfoFeedClarification,
  clearInfoFeedKeywordCache,
  clearInfoFeedRetryState,
  clearInfoFeedSummaryStreamTimer,
  clearInvalidInfoFeedModelReferences,
  compactInfoFeedAttachment,
  compactInfoFeedRunForStorage,
  continueInfoFeedAfterModelSelection,
  continueInfoFeedAfterRetry,
  continueInfoFeedCurrentRun,
  copyInfoFeedSummary,
  createInfoFeedFollowUpContext,
  createInfoFeedRun,
  createInitialInfoFeedAgentState,
  createInitialInfoFeedKeywordState,
  createInitialInfoFeedSummaryState,
  deleteInfoFeedHistory,
  deleteInfoFeedHistoryItem,
  delayMs,
  estimateInfoFeedContextTokens,
  executeInfoFeedRunIteration,
  exportInfoFeedSummary,
  extractInfoFeedClarification,
  fallbackInfoFeedSummary,
  handleInfoFeedAttachmentFiles,
  infoFeedAgentAnswer,
  infoFeedAgentExpertGuidance,
  infoFeedAgentProgressFromResult,
  infoFeedAgentRecentTurns,
  infoFeedAgentSteps,
  infoFeedAllKeywordItems,
  infoFeedAttachments,
  infoFeedCanFollowUp,
  infoFeedClarification,
  infoFeedContextGateNotice,
  infoFeedCurrentRun,
  infoFeedCurrentUserQuestion,
  infoFeedExpertFeedbackFor,
  infoFeedExpertFeedbackForRun,
  infoFeedForm,
  infoFeedHistory,
  infoFeedHistoryPanelItems,
  infoFeedInputPlaceholder,
  infoFeedKeywordCache,
  infoFeedKeywordItems,
  infoFeedKeywordProgressLabel,
  infoFeedKeywordScanExplain,
  infoFeedLowRelevanceKeywordItems,
  infoFeedModelDisplayLabel,
  infoFeedModelOptions,
  infoFeedModelSelectionMessage,
  infoFeedNeedsModelSelection,
  infoFeedNeedsRetryContinue,
  infoFeedParentRunForCurrent,
  infoFeedParentRunSnapshot,
  infoFeedParentSummaryEvidenceRefs,
  infoFeedParentSummaryHtml,
  infoFeedReadyForSummary,
  infoFeedRestorableModelAlias,
  infoFeedRetryMessage,
  infoFeedRetryStageLabel,
  infoFeedRunEvidenceRefs,
  infoFeedRunSequence,
  infoFeedSearchCacheKey,
  infoFeedSourceContextBudgetChars,
  infoFeedSourceResultLine,
  infoFeedSourceSummary,
  infoFeedStreamingSummaryHtml,
  infoFeedSubmitLabel,
  infoFeedSummaryEvidenceRefs,
  infoFeedSummaryIsStreaming,
  infoFeedSummaryMarkdown,
  infoFeedSummaryRuntime,
  infoFeedSummaryStreamText,
  infoFeedSummaryStreamTimer,
  infoFeedTurnAttachments,
  infoFeedTurnQuestion,
  infoFeedTurnSummaryHtml,
  infoFeedTurnTitle,
  infoFeedUserCardTitle,
  infoFeedVisibleSummaryText,
  initialInfoFeedAgentState,
  initialInfoFeedKeywordState,
  initialInfoFeedSummaryState,
  isInfoFeedRetryExhaustedError,
  isLowRelevanceSourceResult,
  isModelConfigurationError,
  isReadableInfoFeedAttachment,
  isTransientFetchError,
  makeInfoFeedId,
  normalizeInfoFeedClarificationOption,
  normalizeInfoFeedHistory,
  openInfoFeedHistoryRun,
  persistInfoFeedHistory,
  readInfoFeedAttachment,
  removeInfoFeedAttachment,
  resetInfoFeedRunForContinuation,
  restoreInfoFeedHistory,
  runInfoFeed,
  runInfoFeedAgentTrack,
  runInfoFeedKeywordTrack,
  runInfoFeedSummaryAgent,
  sanitizeInfoFeedRunModelReferences,
  selectedInfoFeedContextProfile,
  selectedInfoFeedModel,
  selectInfoFeedHistoryItem,
  setInfoFeedRetryState,
  snapshotInfoFeedAttachments,
  snapshotInfoFeedTurn,
  streamInfoFeedSummary,
  syncInfoFeedExpertFeedback,
  upsertInfoFeedHistory,
  withInfoFeedFetchRetry,
} = createConsoleInfoFeedController({
  agentExploreConfiguredLimit,
  agentExploreConfiguredMaxIterations,
  agentExploreContextWindowOptions,
  agentExploreForm,
  agentExploreThinkingModeOptions,
  agentSelectorOptions,
  canReadKnowledge,
  contextProfileRows,
  error,
  recordFeedback: recordConsoleKnowledgeFeedback,
  settingsDraft,
});
const {
  fuseKnowledgeReview,
  knowledgeReviewBusyGeneration,
  knowledgeReviewItems,
  knowledgeReviewRequestGeneration,
  knowledgeReviewStatus,
  pendingKnowledgeReviewCount,
  refreshKnowledgeConflicts,
  resolveKnowledgeReview,
  selectedKnowledgeReviewFusionModel,
  selectedKnowledgeReviewId,
} = createConsoleKnowledgeReviewController({
  agentExploreThinkingParameters,
  agentSelectorOptions,
  canAdminKnowledge,
  canMaintainKnowledge,
  canReadKnowledge,
  clearAllBusy,
  currentView,
  error,
  knowledgeConsole,
  refreshKnowledgeConsole,
  setBusy,
  settingsDraft,
});
watchAgentSelectionReference(
  "info-feed-summary",
  "信息流智能体",
  () => infoFeedForm.value.modelAlias,
  () => selectedInfoFeedModel.value,
);
watchAgentSelectionReference(
  "agent-explore",
  "智能检索",
  () => agentExploreForm.value.modelAlias,
  () => selectedAgentExploreModel.value,
);
watchAgentSelectionReference(
  "rule-authoring",
  "规则编排",
  () => ruleAuthoringForm.value.modelAlias,
  () => selectedRuleAuthoringModel.value,
);
watchAgentSelectionReference(
  "knowledge-review-fusion",
  "知识融合智能体",
  () => settingsDraft.value.agentExploreDefaults?.reviewFusionModelAlias || "",
  () => selectedKnowledgeReviewFusionModel.value,
);
watchAgentSelectionReference(
  "word-cloud",
  "词云生成",
  () => wordCloudModelAlias.value,
  () => selectedWordCloudModel.value,
);
const {
  agentExploreHistoryPanelItems,
  agentExplorePollTimer,
  agentExploreSessionFromResult,
  agentExploreSessionLabel,
  agentExploreTabBusy,
  agentExploreTabs,
  applyAgentExploreDraftTab,
  clearInvalidAgentExploreModelReferences,
  closeAgentExploreTab,
  createAgentExploreDraftTab,
  deleteAgentExploreHistoryItem,
  deleteAgentExploreHistorySession,
  loadAgentExploreHistoryFromServer,
  loadAgentExploreSession,
  normalizeAgentExploreHistoryList,
  persistAgentExploreState,
  resetKnowledgeAgentExplore,
  restoreAgentExploreState,
  runKnowledgeAgentExplore,
  sanitizeAgentExploreSessionModelReference,
  selectAgentExploreHistoryItem,
  startAgentExplorePolling,
  stopAgentExplorePolling,
  switchAgentExploreTab,
  syncActiveAgentExploreDraftFromForm,
  upsertAgentExploreHistory,
} = createConsoleAgentExploreSessionController({
  agentExploreActiveTabId,
  agentExploreClosedTabIds,
  agentExploreDraftTabs,
  agentExploreForm,
  agentExploreHiddenRunIds,
  agentExploreHistory,
  agentExploreHydrated,
  agentExploreResult,
  agentExploreTraceOpen,
  agentExploreDefaults,
  busyKey,
  canReadKnowledge,
  clearAllBusy,
  currentView,
  debugTab,
  error,
  hasAgentModelOption,
  normalizeThinkingMode: normalizedAgentExploreThinkingMode,
  selectedAgentExploreContextProfile,
  selectedAgentExploreModel,
  selectedAgentExploreThinkingMode,
  setBusy,
  validAgentModelAlias,
});
watch(
  agentSelectorOptions,
  (options) => {
    cacheAgentModelOptionLabels(options);
  },
  { immediate: true },
);

const {
  knowledgeSearchEmpty,
  knowledgeSearchExpanded,
} = createConsoleKnowledgeSearchPanelStateController({
  busyKey,
  debugTab,
  knowledgeSearchResults,
  lastKnowledgeSearchQuery,
  selectedEvidence,
});
const {
  openLocalSourceDirectoryPicker,
  openSettingsPathPicker,
  openWordCloudCorpusDirectoryPicker,
  openWordCloudCorpusFilePicker,
} = createConsolePathPickerActionController({
  addWordCloudCorpusPaths,
  applyLocalSourceDirectoryPath,
  localSourceForm,
  openServerPathPicker,
  settingsDraft,
});

function configTargetElement(targetId: string) {
  return configTargetHighlightController.configTargetElement(targetId);
}

async function scrollToConfigTarget(targetId: string) {
  await configTargetHighlightController.scrollToConfigTarget(targetId);
}

function importClients() {
  notifyConsoleAction("导入客户端功能正在开发中…");
}

function exportClients() {
  notifyConsoleAction("导出客户端列表成功。");
}

const refreshStateController = createConsoleRefreshStateController({
  applyConsoleState,
  busyKey,
  clearAllBusy,
  error,
  serverAvailable,
  setBusy,
});
const {
  REFRESH_STATE_DELAY_MS,
  clearPendingRefreshState,
  clearPendingRefreshStateTimer,
  lastRefreshStateStartedAt,
  mergeRefreshStateOptions,
  normalizeRefreshStateOptions,
  pendingRefreshStateOptions,
  pendingRefreshStatePromise,
  pendingRefreshStateResolve,
  pendingRefreshStateTimer,
  performRefreshState,
  refreshState: refreshStateCore,
  scheduleDelayedRefreshState,
} = refreshStateController;

function refreshState(options: RefreshStateOptions = {}) {
  return refreshStateCore(options);
}

async function handleCloudProviderChange() {
  if (hasOpenAiModelUsage()) {
    await ensureCodexOAuthReady(true);
  }
}

bindSettingsPersistenceActions(createConsoleSettingsPersistenceController({
  agentPermissionGroups: () => agentPermissionGroups.value,
  clearAllBusy,
  ensureCodexOAuthReady,
  error,
  hasOpenAiModelUsage,
  modelEntryStatusKey,
  mountDraft,
  mountDraftDirty,
  probeModelLibraryBeforeSave,
  refreshState,
  replaceSettingsDraftFromServer,
  setBusy,
  settingsDraft,
  settingsDraftDirty,
  settingsPayloadForSave,
}));

const {
  activeJobCount,
  deleteJob,
  filteredJobs,
  latestJob,
  recalculateJobSummary,
  recentJobs,
  removeJobFromEvent,
  upsertJobFromEvent,
} = createConsoleJobController({
  applyIngestJobFromEvent,
  applyJobToKnowledgeSources,
  clearAllBusy,
  confirmAction: confirmConsoleAction,
  consoleState,
  error,
  refreshState,
  setBusy,
});

const {
  attentionClientCount,
  clientSearchQuery,
  clientStateFilter,
  clientStateFilterOptionBarOptions,
  displayedClients,
  filteredClientList,
  filteredClients,
  latestClient,
} = createConsoleClientController({
  consoleState,
});

const {
  addableModelProviderOptionBarOptions,
  analysisModuleOptionBarOptions,
  authRoleOptionBarOptions,
  autoApproveRiskOptionBarOptions,
  contextWindowOptionBarOptions,
  discoveryModeOptionBarOptions,
  enabledBooleanOptionBarOptions,
  enabledStringOptionBarOptions,
  moduleAccessModeOptionBarOptions,
  moduleModelAssignmentSelectOptions,
  plannerModeOptionBarOptions,
  thinkingModeOptionBarOptions,
  vocabularyStatusOptionBarOptions,
} = createConsoleOptionBarController({
  addableModelProviders,
  agentExploreContextWindowOptions,
  agentExploreThinkingModeOptions,
  authState,
  consoleState,
  moduleModelAssignmentOptions,
  providerLabel,
});
const {
  agentConfigurationAlertSummary,
  agentConfigurationAlerts,
  dashboardAlertCounts,
  dashboardAlertInbox,
  dashboardAlertInboxId,
  dashboardAlertSummary,
  dashboardAlerts,
  dashboardConfigurationQueue,
  dismissDashboardAlert,
  dismissedDashboardAlertIds,
  dashboardMonitorQueue,
  dashboardPrimaryAlert,
  dashboardSecondaryAlerts,
  liveDashboardAlerts,
  openDashboardAlert,
  refreshDashboardAlertsSnapshot,
  syncDashboardAlertInbox,
} = createConsoleDashboardAlertController({
  acknowledgeMonitorAlert,
  activeMonitorAlerts,
  agentExploreAgentOptions,
  agentExploreForm,
  agentModelAssignmentOptions,
  agentSelectorOptions,
  backgroundProcesses,
  error,
  infoFeedForm,
  infoFeedModelOptions,
  moduleModelRef,
  moduleNeedsIntelligence,
  openAdmin,
  openAgentConfigurationAlert,
  refreshMonitorAlerts,
  recoverBackgroundSupervisor,
  ruleAuthoringForm,
  ruleAuthoringModelOptions,
  settingsDraft,
  visibleModelEntries,
});

const {
  baseServerLogRows,
  collectSystemStatusLogRows,
  compactLogDetail,
  genericStatusTone,
  serverLogRows,
  stateProgressPercent,
} = createConsoleSystemLogRowController({
  activeKnowledgeSources,
  activeMonitorAlerts,
  agentConfigurationAlerts,
  agentSelectionReferenceLogs,
  authAudit,
  backgroundProcesses,
  backgroundProcessStatus,
  knowledgeRecentJobs,
  recentJobs,
  recentMonitorAlertHistory,
  toolManagementAuditItems,
  uploadTraceEvents,
  workQueueRows,
});

const {
  exportKnowledgeLogRows,
  filteredKnowledgeLogRows,
  handleKnowledgeLogColumnDividerKeydown,
  handleKnowledgeLogColumnPointerMove,
  handleKnowledgeLogTableScroll,
  knowledgeLogAdvancedOpen,
  knowledgeLogColumnDividers,
  knowledgeLogColumnLabels,
  knowledgeLogColumnMinWidths,
  knowledgeLogColumnOrder,
  knowledgeLogColumnWidths,
  knowledgeLogFilters,
  knowledgeLogResizing,
  knowledgeLogStatusOptionBarOptions,
  knowledgeLogStatusOptions,
  knowledgeLogTableScrollLeft,
  knowledgeLogTableShellRef,
  startKnowledgeLogColumnResize,
  stopKnowledgeLogColumnResize,
  syncKnowledgeLogTableScrollLeft,
} = createConsoleKnowledgeLogController({
  serverLogRows,
});

watch(
  [currentView, adminView, filteredKnowledgeLogRows],
  () => {
    if (currentView.value === "admin" && adminView.value === "logs") {
      void nextTick(() => syncKnowledgeLogTableScrollLeft());
    }
  },
  { flush: "post" },
);

const serverIdentity = computed(
  () =>
    consoleState.value?.discovery?.value?.serverLabel ||
    consoleState.value?.server.hostname ||
    "Pact Server",
);

const {
  mountConsoleRuntime,
  unmountConsoleRuntime,
} = createConsoleRuntimeLifecycleController({
  authBootstrapping,
  clearBrowserLocalStateFromUrl,
  clearConfigTargetHighlight: () => configTargetHighlightController.clearConfigTargetHighlight(),
  clearInfoFeedSummaryStreamTimer,
  clearPendingRefreshState,
  liveDashboardAlerts,
  refreshAuthState,
  refreshCodexOAuthStatus,
  refreshContextCompiler,
  refreshKnowledgeConsole,
  refreshMonitorAlerts,
  refreshState,
  restoreAgentExploreState,
  restoreInfoFeedHistory,
  startServerEventSubscription,
  stopAgentExplorePolling,
  stopAgentExploreSplitResize,
  stopCodexOAuthPolling,
  stopKnowledgeLogColumnResize,
  stopServerEventSubscription,
  syncDashboardAlertInbox,
});


export function useConsole() {
const _router = useRouter();
const _route = useRoute();
bindNavigationRouter(_router);

// Sync URL → state: when the user navigates via back/forward or direct URL,
// update the module-level navigation refs to match the route.
watch(
  () => _route.fullPath,
  () => {
    syncNavigationStateFromRoute(_route);
  },
  { immediate: true },
);

onMounted(() => {
  mountConsoleRuntime();
});

onUnmounted(() => {
  unmountConsoleRuntime();
});
  return {
    acknowledgeMonitorAlert,
    activeJobCount,
    activeKnowledgeSources,
    activeMonitorAlerts,
    activeToolManagementToolCount,
    addAgentPermissionGroup,
    addChildWordCloud,
    addKnowledgeSource,
    addManualWordCloud,
    addModelProvider,
    addTermActionToCloud,
    addTermInputToCloud,
    addVocabularyEntry,
    addableModelProviderOptionBarOptions,
    adminView,
    agentEvidencePreviewOpen,
    agentExploreActiveTabId,
    agentExploreAgentOptions,
    agentExploreAnswerHtml,
    agentExploreDocumentMarkdown,
    agentExploreEventTime,
    agentExploreForm,
    agentExploreHistoryPanelItems,
    agentExploreLinkedEvidenceRefs,
    agentExploreProgress,
    agentExploreProgressVisible,
    agentExploreResult,
    agentExploreSplitDragging,
    agentExploreSplitLeftPercent,
    agentExploreSplitRef,
    agentExploreSplitStyle,
    agentExploreStepOpen,
    agentExploreSteps,
    agentExploreTabBusy,
    agentExploreTabs,
    agentExploreTraceOpen,
    agentExploreWorkspaceId,
    agentPermissionGroupOptionBarOptions,
    agentPermissionGroups,
    agentSelectorOptions,
    approveMaintenanceAgentRun,
    attentionClientCount,
    authAudit,
    authBootstrapping,
    authRoleOptionBarOptions,
    authSessions,
    authState,
    authUsers,
    autoApproveRiskOptionBarOptions,
    autoFillCloudWithAgent,
    backgroundProcessStatus,
    backgroundProcesses,
    backgroundRunningCount,
    backgroundSupervisorLabel,
    beginCodexOAuthLogin,
    busyKey,
    canAdminAuth,
    canAdminKnowledge,
    canAdminMaintenanceAgent,
    canApproveMaintenanceAgent,
    canBrowseServerPaths,
    canMaintainKnowledge,
    canReadKnowledge,
    canRunMaintenanceAgent,
    canSubmitKnowledgeIngest,
    canWriteJobs,
    canWriteKnowledge,
    cancelMaintenanceAgentRun,
    chatMaintenanceAgent,
    chooseInfoFeedClarification,
    clearRemovedTermsFromCloud,
    clearWordCloudCorpusPaths,
    clientRuntimeHeatRows,
    clientRuntimeSummary,
    clientSearchQuery,
    clientStateFilter,
    clientStateFilterOptionBarOptions,
    closeAgentEvidencePreview,
    closeAgentExploreTab,
    closeDrawer,
    closeServerPathPicker,
    codexOAuthLogin,
    codexOAuthStatus,
    collapsedWordBagIds,
    confirmServerPathPicker,
    consoleState,
    contextBuildRecordRows,
    contextEvaluationResult,
    contextPreviewRequiredEvidence,
    contextPreviewResult,
    contextPreviewTask,
    contextProfileRows,
    contextWindowOptionBarOptions,
    continueInfoFeedAfterModelSelection,
    continueInfoFeedAfterRetry,
    copyAgentExploreDocument,
    copyInfoFeedSummary,
    copyIssuedToolToken,
    createGrant,
    currentAgentModelOptionLabel,
    currentUser,
    currentView,
    dashboardAlertCounts,
    dashboardAlertInboxId,
    dashboardAlertSummary,
    dashboardAlerts,
    dashboardConfigurationQueue,
    dashboardMonitorQueue,
    dashboardPrimaryAlert,
    dashboardSecondaryAlerts,
    debugTab,
    deleteAgentExploreHistoryItem,
    deleteGrant,
    deleteInfoFeedHistoryItem,
    deleteJob,
    deleteKnowledgeSource,
    deleteVocabularyEntry,
    disableMountModule,
    discoveryDraft,
    discoveryDraftDirty,
    discoveryModeOptionBarOptions,
    dismissDashboardAlert,
    displayedMaintenanceAgentRuns,
    displayedVocabularyEntries,
    drawerOpen,
    drawerTab,
    duplicateModelEntry,
    emailReportSeriesRules,
    emailSynonymRules,
    enableMountModule,
    enabledBooleanOptionBarOptions,
    enabledMountCount,
    enabledStringOptionBarOptions,
    enabledToolGrantCount,
    ensureAgentPermissionGroupsDraft,
    error,
    errorNeedsKnowledgeImportAction,
    evidenceLoadError,
    evidenceReadableHtml,
    evidenceReadableKind,
    evidenceSourceDetails,
    externalServiceTab,
    expertRuleEnabled,
    expertVocabularyDraft,
    expertVocabularyDraftDirty,
    exportAgentExploreDocument,
    exportAgentModelEntryConfig,
    exportClients,
    exportContextBuildRecords,
    exportInfoFeedSummary,
    exportKnowledgeLogRows,
    fillingWordBagIds,
    filter,
    filteredClientList,
    filteredKnowledgeLogRows,
    fuseKnowledgeReview,
    goldenRuleItems,
    goldenRulePackageTitle,
    goldenRulePackages,
    grantHasToolset,
    grantToolRuleState,
    handleAgentAnswerClick,
    handleAgentExploreSplitKeydown,
    handleAgentExploreTraceToggle,
    handleInfoFeedAttachmentFiles,
    handleKnowledgeLogTableScroll,
    hasAnyFeature,
    hasFeature,
    hiddenVocabularyEntryCount,
    highlightedConfigTarget,
    importClients,
    infoFeedAgentAnswer,
    infoFeedAgentSteps,
    infoFeedAllKeywordItems,
    infoFeedAttachments,
    infoFeedClarification,
    infoFeedContextGateNotice,
    infoFeedCurrentRun,
    infoFeedCurrentUserQuestion,
    infoFeedExpertFeedbackFor,
    infoFeedExpertFeedbackForRun,
    infoFeedForm,
    infoFeedHistory,
    infoFeedHistoryPanelItems,
    infoFeedInputPlaceholder,
    infoFeedKeywordItems,
    infoFeedKeywordProgressLabel,
    infoFeedLowRelevanceKeywordItems,
    infoFeedModelOptions,
    infoFeedModelSelectionMessage,
    infoFeedNeedsModelSelection,
    infoFeedNeedsRetryContinue,
    infoFeedParentRunForCurrent,
    infoFeedParentSummaryHtml,
    infoFeedReadyForSummary,
    infoFeedRetryMessage,
    infoFeedRetryStageLabel,
    infoFeedStreamingSummaryHtml,
    infoFeedSubmitLabel,
    infoFeedSummaryIsStreaming,
    infoFeedSummaryMarkdown,
    infoFeedSummaryRuntime,
    infoFeedTurnAttachments,
    infoFeedTurnQuestion,
    infoFeedTurnSummaryHtml,
    infoFeedTurnTitle,
    infoFeedUserCardTitle,
    ingestFiles,
    ingestJob,
    ingestProgress,
    intelligentModuleDefinitions,
    internalToolManagementToolCount,
    isAgentExploreDraftSession,
    isAuthenticated,
    isModelLibraryCardExpanded,
    isMountPathEditing,
    issuedToolToken,
    jumpToKnowledgeFileImport,
    knowledgeConfigGroupDescription,
    knowledgeConsole,
    knowledgeIngestExternalProvider,
    knowledgeIngestExternalRefs,
    knowledgeIngestExternalTargetLabels,
    knowledgeIngestTargetValidationMessage,
    knowledgeIngestTargets,
    knowledgeIngestTeamRefs,
    knowledgeIngestUserRefs,
    knowledgeLogAdvancedOpen,
    knowledgeLogColumnWidths,
    knowledgeLogFilters,
    knowledgeLogStatusOptionBarOptions,
    knowledgeLogTableShellRef,
    knowledgeManagementPanel,
    knowledgeManagementPanelOptionBarOptions,
    knowledgeRecallDebugForm,
    knowledgeRecallDebugGridStyle,
    knowledgeRecallDebugModeOptionBarOptions,
    knowledgeRecallDebugRuns,
    knowledgeRecallDebugTargetOptions,
    knowledgeReviewItems,
    knowledgeReviewStatus,
    knowledgeSchema,
    knowledgeSourceState,
    knowledgeStatus,
    knowledgeTab,
    knowledgeTabDisplayLabel,
    latestMaintenanceAgentRun,
    localSourceForm,
    loginForm,
    logoutConsole,
    maintenanceAgentConfig,
    maintenanceAgentMessage,
    maintenanceAgentModelAlias,
    maintenanceAgentResultJson,
    maintenanceAgentRunbook,
    maintenanceAgentRunbookOptionBarOptions,
    maintenanceAgentRunbooks,
    maintenanceAgentSummary,
    maintenanceFieldValue,
    maintenanceJson,
    mcpAuthorizationRequests,
    mcpAuthorizationStatus,
    mcpAuthorizationStatusOptionBarOptions,
    modelEntryBindingSummary,
    modelEntryBindings,
    modelEntryIsBound,
    modelEntryModuleAccess,
    modelEntryProbeResult,
    modelEntryProbeStatusLabel,
    modelEntryProbeStatusTone,
    modelEntryStatusKey,
    modelProbeResults,
    modelProviderDefinition,
    moduleAccessModeOptionBarOptions,
    moduleGroups,
    moduleModelAssignmentSelectOptions,
    moduleModelAssignmentStats,
    moduleModelRef,
    moduleNeedsIntelligence,
    monitorAlertConfigText,
    monitorAlertState,
    monitorAlertSummary,
    mountDraft,
    mountDraftDirty,
    newGrantLabel,
    newGrantScopes,
    newGrantToolsets,
    nextMaintenanceAgentRunAt,
    normalizedManifest,
    oidcAllowedDomainsText,
    oidcDraft,
    oidcRoleMappingText,
    onIngestFilesSelected,
    openAdmin,
    openAgentEvidencePreview,
    openDashboardAlert,
    openDebugTab,
    openDrawer,
    openExternalServiceTab,
    openKnowledgeManagementPanel,
    openKnowledgeTab,
    openLocalSourceDirectoryPicker,
    openMountPathPicker,
    openPathEntry,
    openWordCloudCorpusDirectoryPicker,
    openWordCloudCorpusFilePicker,
    parseModelRef,
    pathEntryMeta,
    pathPicker,
    pathPickerModeLabel,
    pendingMaintenanceApprovalCount,
    permissionGroupHasToolset,
    pinWordCloud,
    pinnedWordBagIds,
    plannerModeOptionBarOptions,
    policyPreviewGrantId,
    policyPreviewProfileId,
    policyPreviewProfileOptionBarOptions,
    policyPreviewResult,
    policyPreviewToolId,
    policyPreviewToolOptionBarOptions,
    previewContextCompiler,
    previewToolPolicy,
    probeModelEntry,
    proposeWordCloud,
    providerLabel,
    publishRuleAuthoringPackage,
    queueMonitorState,
    recentJobs,
    recentMonitorAlertHistory,
    refreshAuthAdmin,
    refreshAuthState,
    refreshBackgroundProcesses,
    refreshClientRuntimeStatus,
    refreshCodexOAuthStatus,
    refreshContextCompiler,
    refreshDashboardAlertsSnapshot,
    recoverBackgroundSupervisor,
    refreshExpertRules,
    refreshIngestJob,
    refreshKnowledgeConflicts,
    refreshKnowledgeConsole,
    refreshKnowledgeSource,
    refreshKnowledgeSources,
    refreshMaintenanceAgent,
    refreshMcpAuthorizationRequests,
    refreshMonitorAlerts,
    refreshServerPathBrowser,
    refreshState,
    refreshToolManagement,
    refreshWordCloud,
    reloadModules,
    removeAgentPermissionGroup,
    removeInfoFeedAttachment,
    removeModelProvider,
    removeTermFromCloud,
    removeWordCloudCorpusPath,
    resetKnowledgeAgentExplore,
    resolveKnowledgeReview,
    resolveMcpAuthorizationRequest,
    revokeConsoleSession,
    rotateGrant,
    ruleActionOptionBarOptions,
    ruleAuthoringCanSubmit,
    ruleAuthoringForm,
    ruleAuthoringModelOptions,
    ruleAuthoringResult,
    ruleCreationMode,
    ruleMatchStrategyOptionBarOptions,
    ruleScopeOptionBarOptions,
    rulesDraftDirty,
    rulesText,
    runContextReplayEvaluation,
    runModelEntryProbe,
    runInfoFeed,
    runInfoFeedSummaryAgent,
    runKnowledgeAgentExplore,
    runKnowledgeRecallDebugBatch,
    runMaintenanceAgentKnowledgeMaintenance,
    runMaintenanceAgentRunbook,
    runRuleAuthoringChat,
    saveAgentPermissionSettings,
    saveDiscovery,
    saveExpertVocabulary,
    saveKnowledgeMaintenance,
    saveMaintenanceAgentConfig,
    saveModelLibrarySettings,
    saveMonitorAlertConfig,
    saveMountModules,
    saveOidcConfig,
    saveRules,
    saveSettings,
    saveWordCloud,
    selectAgentExploreHistoryItem,
    selectInfoFeedHistoryItem,
    selectServerPath,
    selectToolForManagement,
    selectWordCloud,
    selectedAgentExploreModel,
    selectedEvidence,
    selectedEvidenceDisplayTitle,
    selectedEvidenceId,
    selectedInfoFeedModel,
    selectedKnowledgeReviewFusionModel,
    selectedMaintenanceAgentRun,
    selectedModelProvider,
    selectedToolManagementTool,
    selectedWordCloud,
    selectedWordCloudModel,
    serverAvailable,
    serverLogRows,
    setEmailRuleEntryEnabled,
    setGrantToolRule,
    setMaintenanceFieldFromEvent,
    setMaintenanceFieldValue,
    setModelEntryModuleAccessMode,
    setModelEntryPermissionGroup,
    setModuleModelRef,
    setModuleNeedsIntelligence,
    setVocabularyEntryEnabled,
    setWordCloudTermInput,
    settingsDraft,
    settingsDraftDirty,
    showAllVocabularyEntries,
    sideNavOpen,
    startAgentExploreSplitResize,
    submitLoginAuth,
    switchAgentExploreTab,
    switchView,
    syncLocalSourceLabelFromPath,
    thinkingModeOptionBarOptions,
    toggleGoldenRuleEnabled,
    toggleGrantToolset,
    toggleModelEntryModuleAccess,
    toggleModelLibraryCard,
    toggleMountPathEdit,
    toggleNewGrantToolset,
    togglePermissionGroupToolset,
    toggleWordCloudActionMenu,
    toggleWordCloudCollapsed,
    toolGrants,
    toolManagementAuditItems,
    toolManagementCatalogState,
    toolManagementMetricsState,
    toolManagementProfiles,
    toolManagementRiskRows,
    toolManagementStatusRows,
    toolManagementTools,
    toolManagementToolsets,
    toolScopes,
    totalMountCount,
    updateConsoleUser,
    updateConsoleUserRole,
    updateGrant,
    updateKnowledgeSource,
    updateVocabularyDomains,
    updateVocabularyKeywords,
    updateVocabularyPath,
    updateWordCloudField,
    uploadFilesToKnowledge,
    viewTitle,
    visibleDebugTabs,
    visibleKnowledgeTabs,
    visibleModelEntries,
    vocabularyEntryPath,
    vocabularySearch,
    wordBagActionMenuId,
    wordCloudCardRows,
    wordCloudCardStyle,
    wordCloudCorpusPathLabel,
    wordCloudCorpusPathSummary,
    wordCloudCorpusPaths,
    wordCloudDraft,
    wordCloudMessages,
    wordCloudModelAlias,
    wordCloudModelOptions,
    wordCloudPrompt,
    wordCloudState,
    wordCloudTermInputs,
    wordCloudTerms,
    wordCloudVisibleTerms,
    workQueueRows,
    workQueueSummary,
  };
}
