import type { ConsoleAuthSummary } from "../auth-types";
import type { AgentConfigState, AgentSelectorState, AgentSettings } from "./agent";
import type { DiscoveryClientsResponse, DiscoveryConfigResponse, FeatureRuntimeSummary, RuntimeInfoResponse } from "./runtime";
import type { EmailRuleSetPayload, ExpertVocabularyResponse, KnowledgeConsoleState, KnowledgeTaxonomyResponse } from "./knowledge";
import type { MaintenanceAgentSummary } from "./maintenance";
import type { ClientRuntimeStatus } from "./ops";
import type { SplitJobListResponse } from "./split";
import type { V001BaselineStatus } from "./production-health";
export type ServerConsoleState = {
  server: RuntimeInfoResponse["server"];
  runtime: RuntimeInfoResponse["runtime"];
  settings: {
    path: string;
    value: AgentSettings;
  };
  agentSelector?: AgentSelectorState;
  agentConfigs?: AgentConfigState;
  discovery: DiscoveryConfigResponse;
  emailRules: EmailRuleSetPayload;
  expertVocabulary: ExpertVocabularyResponse;
  knowledgeTaxonomy: KnowledgeTaxonomyResponse;
  auth?: ConsoleAuthSummary | null;
  maintenanceAgent?: MaintenanceAgentSummary | null;
  knowledgeConsole?: KnowledgeConsoleState | null;
  storage: RuntimeInfoResponse["storage"];
  v001Baseline?: V001BaselineStatus | null;
  jobs: SplitJobListResponse;
  clients: DiscoveryClientsResponse;
  clientRuntime?: ClientRuntimeStatus | null;
  features?: FeatureRuntimeSummary | null;
};
